COLUMNS:
 0   Id                  : int64 
 1   Income             :  int64 
 2   Age                :  int64 
 3   Experience         :  int64 
 4   Married/Single     :  object
 5   House_Ownership    :  object
 6   Car_Ownership      :  object
 7   Profession         :  object
 8   CITY               :  object
 9   STATE              :  object
 10  CURRENT_JOB_YRS    :  int64 
 11  CURRENT_HOUSE_YRS  :  int64 
 12  Risk_Flag           : int64 

 
TARGET_COLUMN:
  name: Risk_Flag